### ISSUE TITLE
iOS 12.3.1 Can't get key for CameraRollDomain-Media

### ISSUE THREAD

**Issue by tweinreich** [dunhamsteve/ios#8]
I tried to extract the `CameraRollDomain` without success - for every picture the LOG writes `No key for protection class 3` and `Can't get key for CameraRollDomain-Media/DCIM/...`. Listing with `ls` however succeeds.

The backup is unencrypted and was created on OS X 10.9.5.

Any idea what I could try differently?

**Edit:**
I also tried to extract a few of the `whatsapp` domains with the same result.

**Comment by dunhamsteve** [comment]
Sorry I haven't had time yet to test with an unencrypted archive.  It could be that backups without passwords are now encrypted with keys stored on the phone, or it could be that my code is broken. (I only use it with password-protected archives, because the keychain can't be decoded otherwise.)

It should work if you can set a password on your backup.

**Comment by tweinreich** [comment]
Hey @dunhamsteve - nothing to be sorry for, I just wanted to leave an issue here at least so you know about it.

I accomplished my goal with [iTunes_Backup_Reader](https://github.com/jfarley248/iTunes_Backup_Reader) in the meantime. 

Thanks for sharing your work with us.
